version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  deploy-to-web:
    executor:
      name: node/default
    steps:
      - run: ssh ${SSH_USER}@${SSH_HOST}
      - run: cd CoinsTerminal
      - run: git clone ${GITHUB_SSH_REPO_URL}
      - run: npm install
      - run: cd socketserver
      - run: pm2 start npm -- start
workflows:
  deploy-to-web:
    jobs:
      - deploy-to-web:
          filters:
            branches:
              only: master
