version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  deploy-to-web:
    executor:
      name: node/default
    steps:
      - run: |
        ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} 
        "
        cd CoinsTerminal &&
        git pull &&
        npm install &&
        cd socketserver &&
        pm2 start npm -- start
        "
workflows:
  deploy-to-prod:
    jobs:
      - deploy-to-web:
          filters:
            branches:
              only: master

