version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  deploy-to-web:
    executor:
      name: node/default
    steps:
      - run:
          name: SSH script
          command: |
            ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "
            if [ -d CoinsTerminal ]; then
              cd CoinsTerminal
              git pull
            else
              git clone ${GITHUB_SSH_REPO_URL}
              cd CoinsTerminal
            fi
            cd socketserver
            npm install
            pm2 start npm -- start"
workflows:
  deploy-to-prod:
    jobs:
      - deploy-to-web:
          filters:
            branches:
              only: master

